name: Deploy

on:
  workflow_dispatch:

env:
  ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
  ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: JDK setup
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto

      - name: Mac deploy
        run: ./gradlew publish --no-daemon --stacktrace
